# Generated by Django 3.0.8 on 2020-08-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=64, verbose_name='Отчество')),
                ('second_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('status', models.CharField(max_length=64, verbose_name='Статус')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP-статус')),
                ('serial', models.PositiveIntegerField(verbose_name='Серия паспорта')),
                ('number', models.PositiveIntegerField(verbose_name='Номер паспорта')),
                ('police_department', models.CharField(max_length=250, verbose_name='Кем выдан')),
                ('police_department_id', models.PositiveIntegerField(verbose_name='Код подразделения')),
                ('date_issue', models.DateField(verbose_name='Дата выдачи')),
                ('sex', models.CharField(choices=[('male', 'муж'), ('femail', 'жен')], default='male', max_length=10, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=300, verbose_name='Место рождения')),
                ('registration', models.CharField(max_length=450, verbose_name='Адрес регистрации')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
    ]
