# Generated by Django 3.1 on 2020-08-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(max_length=64, null=True, verbose_name='Статус'),
        ),
    ]
