# Generated by Django 3.1 on 2020-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('revoked', 'Отказ'), ('close', 'Закрыт')], default='open', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
