# Generated by Django 3.1 on 2020-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200824_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('close', 'Закрыт')], default='open', max_length=30, verbose_name='Статус заказа'),
        ),
    ]
