# Generated by Django 3.0.8 on 2020-07-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(verbose_name='Номер апартамента')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('busy', 'Занят'), ('booking', 'Забронирован'), ('maintenance', 'На обслуживании')], default='free', max_length=25, verbose_name='Статус')),
                ('day_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Стоимость за сутки')),
                ('night_price', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Стоимость за ночь')),
                ('apartment_type', models.CharField(choices=[('luxary', 'Люкс'), ('halfluxury', 'Полу-люкс'), ('standart', 'Стандарт'), ('economy', 'Эконом'), ('married', 'Для молодожен')], default='standart', max_length=25, verbose_name='Тип')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='Этаж')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('id_clients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Client')),
                ('id_orders', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Апартамент',
                'verbose_name_plural': 'Апартаменты',
                'db_table': 'apartments',
            },
        ),
    ]
