# Generated by Django 3.0.8 on 2020-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер апартамента'),
        ),
    ]
