# Generated by Django 3.0.8 on 2020-07-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20200721_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='day_price',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Стоимость за сутки'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='night_price',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Стоимость за ночь'),
        ),
    ]
