# Generated by Django 5.0 on 2023-12-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apartments", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Открыт"), ("close", "Закрыт")],
                        default="open",
                        max_length=30,
                        verbose_name="Статус заказа",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата открытия заказа")),
                (
                    "date_end",
                    models.DateField(null=True, verbose_name="Дата закрытия заказа"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Таймштамп"),
                ),
                (
                    "id_apartment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="apartments.apartment",
                    ),
                ),
                (
                    "id_client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "orders",
            },
        ),
    ]
